# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[en]
languageName = "En"
languageCode = "en-us"
weight = 1

# ------------------------------------------------------------
# Indonesia language
# ------------------------------------------------------------
[id]
languageName = "Id"
languageCode = "id-ID"
weight = 2