# ------------------------------------------------------------
# English language
# ------------------------------------------------------------
[en]
languageName = "English"
languageCode = "en-us"
weight = 1

# ------------------------------------------------------------
# Indonesia language
# ------------------------------------------------------------
[id]
languageName = "Indonesian"
languageCode = "id-ID"
weight = 2