############# French navigation ##############

[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Faq"
url = "faq/"
weight = 2

[[main]]
name = "Kontak"
url = "contact/"
weight = 3
